name: Diagnostic Workflow

on:
  push:
    branches:
      - main

jobs:
  diagnose-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 1. List files recursively
      run: ls -R
      
    - name: 2. Show content of Solution File (.sln)
      run: cat *.sln

    - name: 3. Show content of API Project File (.csproj)
      run: cat ./ContentHub/ContentHub.csproj

    - name: 4. Show content of Test Project File (.csproj)
      run: cat ./ContentHub.Tests/ContentHub.Tests.csproj
      
    - name: 5. Show .NET Info
      run: dotnet --info