name: Deploy to azure app services
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/contenthub-api:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/contenthub-api:${{ github.sha }}

    - name: Deploy to azure app service
      uses: azure/webapps-deploy@v3
      with:
          app-name: 'wirtzcontenthubapi'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/contenthub-api:${{ github.sha }}'


